name: Deploy storybook on Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Build storybook
        run: npm run build-storybook

      - name: Build and deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-static